# 환영합니다 {.unnumbered}

이 웹사이트는 **"R for Data Science"** (R을 활용한 데이터 과학) 제2판을 위한 곳입니다.
이 책은 R을 사용하여 데이터 과학을 수행하는 방법을 알려줍니다. 데이터를 R로 가져오고, 가장 유용한 구조로 만들고, 변형하고, 시각화하는 방법을 배우게 됩니다.

이 책에서 데이터 과학을 위한 실습 기술을 찾을 수 있습니다.
화학자가 시험관을 세척하고 실험실을 비축하는 법을 배우는 것처럼, 데이터를 정제하고 도표를 그리는 법, 그리고 그 외의 많은 것들을 배우게 될 것입니다.
이것들은 데이터 과학이 가능하게 하는 기술들이며, 여기에서 R로 이러한 각각의 작업을 수행하기 위한 모범 사례를 찾을 수 있습니다.
시간을 절약하기 위해 그래픽 문법(grammar of graphics), 문학적 프로그래밍(literate programming), 재현 가능한 연구(reproducible research)를 사용하는 방법을 배우게 됩니다.
또한 데이터를 랭글링(wrangling), 시각화 및 탐색할 때 발견을 촉진하기 위해 인지 자원을 관리하는 방법도 배우게 됩니다.

이 웹사이트는 [CC BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/us/) 라이선스에 따라 언제나 무료로 제공됩니다.
책의 실물 사본을 원하시면 [Amazon](https://www.amazon.com/dp/1492097403?&tag=hadlwick-20)에서 주문할 수 있습니다.
이 책을 무료로 읽는 것에 감사하며 보답하고 싶다면, [Kākāpō Recovery](https://www.doc.govt.nz/kakapo-donate)에 기부해 주세요. (R4DS 표지에 등장하는) [카카포(kākāpō)](https://www.youtube.com/watch?v=9T1vfsHYiKY)는 뉴질랜드 자생의 심각한 멸종 위기 앵무새로, 단 244마리만 남아 있습니다.

다른 언어를 사용하신다면, 무료로 이용 가능한 1판 번역본에 관심이 있으실 수 있습니다:

-   [스페인어](http://es.r4ds.hadley.nz)
-   [이탈리아어](https://it.r4ds.hadley.nz)
-   [터키어](https://tr.r4ds.hadley.nz)
-   [포르투갈어](https://pt.r4ds.hadley.nz)

그리고 2판 번역본:

-   [스페인어](https://davidrsch.github.io/r4ds-es/)

책의 연습문제에 대한 제안 답안은 <https://mine-cetinkaya-rundel.github.io/r4ds-solutions>에서 찾을 수 있습니다.

R4DS는 [기여자 행동 강령(Contributor Code of Conduct)](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html)을 따릅니다.
이 책에 기여함으로써 귀하는 해당 약관을 준수하는 데 동의하는 것입니다.